include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_fields: false  # Desactiva la advertencia de hacer final los campos privados
    avoid_print: true  # Evita el uso de print en el código, usa debugPrint en su lugar
    prefer_const_constructors: true  # Sugiere el uso de constructores constantes cuando sea posible
    prefer_const_literals_to_create_immutables: true  # Sugiere el uso de constantes para listas y mapas
    unnecessary_null_checks: true  # Evita verificaciones nulas innecesarias
    always_use_package_imports: true  # Evita importaciones relativas dentro del proyecto
    unnecessary_this: true  # Evita el uso innecesario de "this" en las variables de clase
    prefer_single_quotes: true  # Prefiere el uso de comillas simples en lugar de dobles
    unnecessary_late: true  # Evita el uso innecesario de "late"
    sized_box_for_whitespace: true  # Sugiere usar SizedBox en lugar de Container para espacios vacíos
