name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.5
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  video_player: ^2.8.2
  video_player_web: ^2.0.17
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.7
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/FeedBack/
    - assets/Botones/
    - assets/Logo/
    - assets/Extras/
    - assets/Imagenes/
    - assets/Textos/
    - assets/videos/Escena1.mp4
    - assets/videos/Escena2.mp4
    - assets/videos/Escena3.mp4
    - assets/videos/Escena3_1.mp4
    - assets/videos/Escena3_2.mp4
    - assets/videos/Escena4.mp4
    - assets/videos/Escena4_1.mp4
    - assets/videos/Escena4_2.mp4
    - assets/videos/Escena5.mp4
    - assets/videos/Escena5_1.mp4
    - assets/videos/Escena5_2.mp4
    - assets/videos/FinalBueno.mp4
    - assets/videos/FinalMalo.mp4
    - assets/videos/FinalNeutro.mp4
    - assets/FeedBack/exito.png
    - assets/FeedBack/fracaso.png
    - assets/Botones/left.svg
    - assets/Botones/right.svg
    - assets/Botones/left.png
    - assets/Botones/right.png
    - assets/Botones/Exit.svg
    - assets/Botones/Play.png
    - assets/Botones/Pause.png
    - assets/Botones/Salir_Pausa.png
    - assets/Botones/Reaunudar_Pausa.png
    - assets/Botones/Iniciar_Home.png
    - assets/Botones/Salir_Home.png
    - assets/Botones/Continuar_Decision.png
    - assets/Logo/Logo.png
    - assets/Logo/LogoAppIntro.png
    - assets/Logo/LogoInicioApp.svg
    - assets/Imagenes/Pantalla_Carga.png
    - assets/Extras/Barra_Progreso.png
    - assets/Imagenes/Final_Neutral.png
    - assets/Imagenes/Final_Negativo.png
    - assets/Imagenes/Final_Positivo.png
    - assets/Imagenes/Pantalla_Inicial.png
    - assets/Imagenes/Pantalla_Logo.png
    - assets/Imagenes/Pantalla_Carga.png
    - assets/Textos/TituloApp.png
    - assets/Sounds/ButonIniciarExperiencia.mp3
    - assets/Sounds/ButonSalir.mp3

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  color: "#000000" # Color de respaldo
  background_image: assets/Imagenes/Pantalla_Carga.png
