name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Íconos de Cupertino para UI en iOS
  cupertino_icons: ^1.0.8

  # Selector de imágenes y videos desde galería
  image_picker: ^1.0.4

  # Manejo de almacenamiento local (archivos, rutas)
  path_provider: ^2.1.5

  # Cliente HTTP para descargar archivos/videos
  dio: ^5.8.0+1

  # Reproductor de video para Flutter
  video_player: ^2.8.2

  # Soporte de video para Flutter Web
  video_player_web: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/VideoEjemplo.mp4


